### ISSUE TITLE
Reutilizar node-tuc

### ISSUE THREAD

**Issue by paulomcnally** [nodenica/tuc-cli#1]
@oscarmcm podrías usar https://github.com/nodenica/node-tuc para este repo.

:+1: 

Aqui hay una implementación en ruby para Slack (usando lita) https://github.com/rubyni/lita-tuc, seria genial tener la version para node/slack.

**Comment by oscarmcm** [comment]
[Por aqui lo uso](https://github.com/nodenica/tuc-cli/blob/master/cli.js#L4)
