### ISSUE TITLE
meow convierte el argumento en un número por object-assign

### ISSUE THREAD

**Issue by paulomcnally** [nodenica/tuc-cli#3]
@oscarmcm si no usaras meow el argumento siempre sería un string y no tendría que usar la función pad.

demo.js

```
var input = process.argv.slice(2);
console.log(input);
console.log(typeof input[0]); // string
```

Ejemplo
    $ node demo.js 00758888

Mira este ejemplo:

http://www.nodenica.com/training/crear-una-interfaz-de-linea-de-comando-cli-con-nodejs

Ya clone tu repo e hice las pruebas y definitivamente el argumento es de tipo numérico gracias a https://github.com/sindresorhus/object-assign/blob/master/index.js

**Comment by oscarmcm** [comment]
Si, el objetivo de usar meow es por la simpleza y por que soporta es6... tengo pensado mover node-tuc a es6 en algun momento y dejar de usar tantos prototypes. Se ve medio extraña la funcion pad ahi y de hecho deberia de ser el modulo quien se encargue de validar si es un entero o una cadena y si tiene 8 caracteres o no, pero funciona por ahora, veremos que sale en futuras versiones.
